// 필터 카테고리 및 필터 목록
export const FILTER_CATEGORIES = [
  { id: "basic", name: "기본" },
  { id: "highteen", name: "하이틴" },
  { id: "kitsch", name: "키치" },
  { id: "popcity", name: "팝시틴" },
  { id: "pastel", name: "파스텔" },
  { id: "retro", name: "레트로" },
  { id: "y2k", name: "Y2K" },
  { id: "dreamy", name: "드림" },
  { id: "vintage", name: "빈티지" },
  { id: "analog", name: "아날로그" },
  { id: "neon", name: "네온" },
  { id: "cinema", name: "시네마" },
  { id: "spring", name: "봄" },
  { id: "summer", name: "여름" },
  { id: "fall", name: "가을" },
  { id: "winter", name: "겨울" },
];

// 필터 데이터
export const FILTERS = {
  basic: [
    { id: "normal", name: "Normal" },
    { id: "brightness", name: "Brightness" },
    { id: "contrast", name: "Contrast" },
  ],
  highteen: [
    { id: "pinkPop", name: "PinkPop" },
    { id: "glamJam", name: "GlamJam" },
    { id: "teenGlow", name: "TeenGlow" },
    { id: "sugarHi", name: "SugarHi" },
    { id: "bubbleUp", name: "BubbleUp" },
    { id: "crushOn", name: "CrushOn" },
    { id: "lilPop", name: "LilPop" },
    { id: "cherryZing", name: "CherryZing" },
    { id: "glowGal", name: "GlowGal" },
    { id: "dollyMix", name: "DollyMix" },
  ],
  kitsch: [
    { id: "ultraCrush", name: "UltraCrush" },
    { id: "moodDust", name: "MoodDust" },
    { id: "popGlow", name: "PopGlow" },
    { id: "colorShot", name: "ColorShot" },
    { id: "moodDrip", name: "MoodDrip" },
    { id: "glowBuzz", name: "GlowBuzz" },
    { id: "colorJam", name: "ColorJam" },
    { id: "lightSnap", name: "LightSnap" },
    { id: "megaDrop", name: "MegaDrop" },
    { id: "glowCrush", name: "GlowCrush" },
  ],
  popcity: [
    { id: "popTime", name: "PopTime" },
    { id: "superDream", name: "SuperDream" },
    { id: "colorMood", name: "ColorMood" },
    { id: "waveRush", name: "WaveRush" },
    { id: "ultraPop", name: "UltraPop" },
    { id: "glowMix", name: "GlowMix" },
    { id: "sweetWave", name: "SweetWave" },
    { id: "lightSnap", name: "LightSnap" },
    { id: "moodShot", name: "MoodShot" },
    { id: "pixelWave", name: "PixelWave" },
  ],
  pastel: [
    { id: "megaGlow", name: "MegaGlow" },
    { id: "glowBuzz", name: "GlowBuzz" },
    { id: "softMood", name: "SoftMood" },
    { id: "brightRush", name: "BrightRush" },
    { id: "sugarJam", name: "SugarJam" },
    { id: "brightMood", name: "BrightMood" },
    { id: "sugarPop", name: "SugarPop" },
    { id: "sugarVibe", name: "SugarVibe" },
    { id: "neoHit", name: "NeoHit" },
    { id: "ultraGlow", name: "UltraGlow" },
  ],
  retro: [
    { id: "sugarRush", name: "SugarRush" },
    { id: "colorRush", name: "ColorRush" },
    { id: "glowWave", name: "GlowWave" },
    { id: "creamCrush", name: "CreamCrush" },
    { id: "glowShot", name: "GlowShot" },
    { id: "lilDream", name: "LilDream" },
    { id: "sugarVibe", name: "SugarVibe" },
    { id: "lilRush", name: "LilRush" },
    { id: "moodTime", name: "MoodTime" },
    { id: "creamHit", name: "CreamHit" },
  ],
  y2k: [
    { id: "moodRush", name: "MoodRush" },
    { id: "vibeZone", name: "VibeZone" },
    { id: "retroShot", name: "RetroShot" },
    { id: "dreamPop", name: "DreamPop" },
    { id: "neonVibe", name: "NeonVibe" },
    { id: "pixelDust", name: "PixelDust" },
    { id: "glowPop", name: "GlowPop" },
    { id: "sweetDream", name: "SweetDream" },
    { id: "ultraVibe", name: "UltraVibe" },
    { id: "popDust", name: "PopDust" },
  ],
  dreamy: [
    { id: "dreamyGlow", name: "DreamyGlow" },
    { id: "softLight", name: "SoftLight" },
    { id: "pastelDream", name: "PastelDream" },
    { id: "mistMood", name: "MistMood" },
    { id: "cloudyVibe", name: "CloudyVibe" },
    { id: "fairyDust", name: "FairyDust" },
    { id: "etherealPop", name: "EtherealPop" },
    { id: "dreamWave", name: "DreamWave" },
    { id: "angelicGlow", name: "AngelicGlow" },
    { id: "heavenlyMist", name: "HeavenlyMist" },
  ],
  vintage: [
    { id: "retroGlow", name: "RetroGlow" },
    { id: "filmGrain", name: "FilmGrain" },
    { id: "analogVibe", name: "AnalogVibe" },
    { id: "oldSchool", name: "OldSchool" },
    { id: "classicTone", name: "ClassicTone" },
    { id: "timeless", name: "Timeless" },
    { id: "nostalgic", name: "Nostalgic" },
    { id: "retroMood", name: "RetroMood" },
    { id: "vintageWave", name: "VintageWave" },
    { id: "antiqueHue", name: "AntiqueHue" },
  ],
  analog: [
    { id: "filmRoll", name: "FilmRoll" },
    { id: "grainyMood", name: "GrainyMood" },
    { id: "kodakGold", name: "KodakGold" },
    { id: "portra400", name: "Portra400" },
    { id: "fujiPro", name: "FujiPro" },
    { id: "ektar100", name: "Ektar100" },
    { id: "tMax400", name: "TMax400" },
    { id: "ilford", name: "Ilford" },
    { id: "polaroid", name: "Polaroid" },
    { id: "instaxMini", name: "InstaxMini" },
  ],
  neon: [
    { id: "neonDream", name: "NeonDream" },
    { id: "cyberpunk", name: "Cyberpunk" },
    { id: "synthwave", name: "Synthwave" },
    { id: "vaporwave", name: "Vaporwave" },
    { id: "neonNoir", name: "NeonNoir" },
    { id: "retrowave", name: "Retrowave" },
    { id: "neonPop", name: "NeonPop" },
    { id: "nightGlow", name: "NightGlow" },
    { id: "cityLights", name: "CityLights" },
    { id: "neonHaze", name: "NeonHaze" },
  ],
  cinema: [
    { id: "movieTone", name: "MovieTone" },
    { id: "filmLook", name: "FilmLook" },
    { id: "cinematic", name: "Cinematic" },
    { id: "hollywood", name: "Hollywood" },
    { id: "blockbuster", name: "Blockbuster" },
    { id: "silverScreen", name: "SilverScreen" },
    { id: "anamorphic", name: "Anamorphic" },
    { id: "technicolor", name: "Technicolor" },
    { id: "noirStyle", name: "NoirStyle" },
    { id: "filmNoir", name: "FilmNoir" },
  ],
  spring: [
    { id: "cherryBlossom", name: "CherryBlossom" },
    { id: "springLight", name: "SpringLight" },
    { id: "pastelBloom", name: "PastelBloom" },
    { id: "freshMorning", name: "FreshMorning" },
    { id: "flowerPop", name: "FlowerPop" },
    { id: "springDew", name: "SpringDew" },
    { id: "gardenGlow", name: "GardenGlow" },
    { id: "bloomDay", name: "BloomDay" },
    { id: "springHaze", name: "SpringHaze" },
    { id: "floralDream", name: "FloralDream" },
  ],
  summer: [
    { id: "sunKissed", name: "SunKissed" },
    { id: "beachDay", name: "BeachDay" },
    { id: "tropicalVibe", name: "TropicalVibe" },
    { id: "summerGlow", name: "SummerGlow" },
    { id: "oceanBreeze", name: "OceanBreeze" },
    { id: "sunsetMood", name: "SunsetMood" },
    { id: "palmShade", name: "PalmShade" },
    { id: "islandLife", name: "IslandLife" },
    { id: "summerHaze", name: "SummerHaze" },
    { id: "beachGlow", name: "BeachGlow" },
  ],
  fall: [
    { id: "autumnGlow", name: "AutumnGlow" },
    { id: "fallMood", name: "FallMood" },
    { id: "goldenHour", name: "GoldenHour" },
    { id: "mapleRed", name: "MapleRed" },
    { id: "fallBreeze", name: "FallBreeze" },
    { id: "octoberSky", name: "OctoberSky" },
    { id: "autumnMist", name: "AutumnMist" },
    { id: "fallSunset", name: "FallSunset" },
    { id: "harvestMoon", name: "HarvestMoon" },
    { id: "fallDream", name: "FallDream" },
  ],
  winter: [
    { id: "frostGlow", name: "FrostGlow" },
    { id: "snowDay", name: "SnowDay" },
    { id: "winterMist", name: "WinterMist" },
    { id: "iceBlue", name: "IceBlue" },
    { id: "winterNight", name: "WinterNight" },
    { id: "crystalClear", name: "CrystalClear" },
    { id: "snowLight", name: "SnowLight" },
    { id: "frostMood", name: "FrostMood" },
    { id: "winterDream", name: "WinterDream" },
    { id: "glacierBlue", name: "GlacierBlue" },
  ],
};
